# Generated by Django 5.2.13 on 2026-05-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_rating"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_rating_per_session",
        ),
        migrations.AlterUniqueTogether(
            name="artigolike",
            unique_together={("artigo", "session_key")},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("artigo", "session_key")},
        ),
    ]
