# Generated by Django 5.2.13 on 2026-06-07 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "prioridade",
                    models.IntegerField(
                        choices=[(1, "Baixa"), (2, "Media"), (3, "Alta")],
                        default=2,
                        help_text="1=Baixa, 2=Media, 3=Alta",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("concluida", models.BooleanField(default=False)),
                ("data_limite", models.DateField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["concluida", "-prioridade", "data_limite", "titulo"],
            },
        ),
    ]
